<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('users')->insert([           
            [
                'name' => 'Marcio Lamonica',
                'email' => 'marciolamonica@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ana Cristina de Souza Cruz Ribeiro',
                'email' => 'aribeiro@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anderson Carvalho Pereira',
                'email' => 'apereira@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anderson Luiz Linhares Rebechi',
                'email' => 'arebechi@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Andrea Ferreira da Silva',
                'email' => 'afsilva@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Angelica Teixeira Quadros',
                'email' => 'aquadros@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arthur Carvalho Laurindo',
                'email' => 'alaurindo@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arthur Pontes Meloni dos Reis',
                'email' => 'areis@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bernardo Julianelli',
                'email' => 'bjulianelli@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Caio Menezes Repani de Azevedo',
                'email' => 'cazevedo@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carlos Vitor Pereira Gomes',
                'email' => 'cgomes@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Claudio Barbosa Ribeiro',
                'email' => 'cribeiro@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cremilson Correa Santos',
                'email' => 'csantos@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cristiano Ribeiro Vieira',
                'email' => 'cvieira@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Daniel Rodrigo Pereira do Nascimento',
                'email' => 'dnascimento@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Douglas de Castro da Silva',
                'email' => 'dsilva@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ébano George Alencar de Almeida',
                'email' => 'ealmeida@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eliel de Jesus Gonçalves',
                'email' => 'marinsrebechi@sequoiabrasil.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eric Jason Urban',
                'email' => 'eurban@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Etiquetas da Produção',
                'email' => 'etiquetas@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Evandro Antonio Vargas',
                'email' => 'evargas@sequoiabrasil-shasta.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fabiana  de Oliveira Amorim',
                'email' => 'famorim@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fabiana de Moura Alves',
                'email' => 'falves@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fabiano Guarnieri Aquino',
                'email' => 'faquino@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fabiano Padua Domingues',
                'email' => 'fdomingues@sequoiabrasil-ocotillo.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fabio Arthur Camacho de Azeredo',
                'email' => 'fazeredo@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fabio Brazil Ribeiro',
                'email' => 'fbribeiro@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fagno Lima Figueiredo',
                'email' => 'ffigueiredo@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Felipe Gonçalves Guimarães',
                'email' => 'fguimaraes@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Felipe Polceno de Araujo',
                'email' => 'faraujo@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fernanda Gonçalves',
                'email' => 'fgoncalves@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Filipe Scaldaferri',
                'email' => 'fscaldaferri@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gabriel dos Santos Barcello',
                'email' => 'gbarcello@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gary Urban',
                'email' => 'gary@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gilvan Alves de Freitas',
                'email' => 'gfreitas@sequoiabrasil-ocotillo.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Heitor Pinto da Cunha',
                'email' => 'hcunha@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hesteffani de Oliveira Martelete',
                'email' => 'hmartelete@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Higor Menegussi Xavier',
                'email' => 'hxavier@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ian Serrado Frutuoso',
                'email' => 'ifrutuoso@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Isabela Pinto dos Santos Cordeiro',
                'email' => 'icordeiro@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Isabella de Carvalho Magalhães',
                'email' => 'imagalhaes@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jaqueline Marinho de Castro',
                'email' => 'jcastro@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jesse Rocha da Cunha',
                'email' => 'jcunha@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jhone de Andrade Barbosa',
                'email' => 'jbarbosa@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'João Pedro Rocha Siqueira',
                'email' => 'jsiqueira@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Julia Rodrigues Gago Andrade',
                'email' => 'jandrade@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Julia Rossi Guimarães',
                'email' => 'jguimaraes@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Juliane Lopes da Silva',
                'email' => 'jsilva@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Karine Viana Barreto Pinto',
                'email' => 'kbarreto@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Katia Regina Pereira Gomes',
                'email' => 'kgomes@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Larissa da Silva Pinto',
                'email' => 'lsilva@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Larissa Melo Rebelo Lima',
                'email' => 'lmlima@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leandro Paranhos Mundim',
                'email' => 'lmundim@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leonardo Santos Franco',
                'email' => 'lfranco@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luan Miguel Pereira Zo Cavalcanti',
                'email' => 'lcavalcanti@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luis Fernando de Oliveira Lemos',
                'email' => 'llemos@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luiz Francisco Grossi',
                'email' => 'lgrossi@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luiz Philipe Rocha de Oliveira',
                'email' => 'loliveira@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manuella Vilar Pereira da Silva',
                'email' => 'mvsilva@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maria Clara Alves Pinto',
                'email' => 'mpinto@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maria Luiza Camacho Batista',
                'email' => 'mbatista@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maria Luiza Soares da Silva',
                'email' => 'mlsilva@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mariana Magalhães Pinto',
                'email' => 'mmpinto@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Miriã da Silva de Andrade',
                'email' => 'mandrade@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Natalia Lopes Tavares',
                'email' => 'ntavares@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Neilo Pinto Carneiro',
                'email' => 'ncarneiro@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nilton Cézar Estêvão Pinto',
                'email' => 'npinto@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Packaging Brands',
                'email' => 'packaging@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pamela de Lima Oliveira',
                'email' => 'poliveira@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paula Lopes da Silva Pinto',
                'email' => 'plopes@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pedro Henrique Reis da Silva',
                'email' => 'phsilva@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pedro Jose Barbosa Repani',
                'email' => 'prepani@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pedro Martins Albuquerque',
                'email' => 'palbuquerque@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phelipe Mariano Curty Soares',
                'email' => 'psoares@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Priscilla Martins de Oliveira',
                'email' => 'pmartins@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rafaella Mendes Fortunato',
                'email' => 'rfortunato@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rebeca Herculano Menezes',
                'email' => 'rmenezes@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Renan Machado do Nascimento',
                'email' => 'rnascimento@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Renan Ramos da Anunciação',
                'email' => 'ranunciacao@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Renata Gralato do Nascimento Araujo',
                'email' => 'raraujo@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Renato Barroso de Sousa',
                'email' => 'rbsousa@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rodolfo Pinheiro Morais Izidoro',
                'email' => 'rizidoro@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rosiane de Souza Silva',
                'email' => 'rssilva@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sandro Marcos Menezes da Rocha',
                'email' => 'srocha@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sara Soares Tobias da Costa',
                'email' => 'scosta@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sarah Ianae Gueths Laguna',
                'email' => 'slaguna@sequoiabrasil-shasta.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Segurança  do Trabalho',
                'email' => 'seguranca@sequoiabrasil.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Solange Ferreira de Carvalho',
                'email' => 'scarvalho@sequoiabrasil-ocotillo.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stefany Alves Silva de Almeida',
                'email' => 'salmeida@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Symoni Marins Rebechi',
                'email' => 'srebechi@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Taiana Santana França',
                'email' => 'tsantana@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tatiane Priscila Tavares do Carmo',
                'email' => 'tcarmo@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tatyane Vieira Marchioro',
                'email' => 'tmarchioro@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thais da Silva e Silva',
                'email' => 'tsilva@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thamires Fernandes Machado',
                'email' => 'tmachado@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Valerie Urban',
                'email' => 'vurban@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vanessa Soares de Azevedo',
                'email' => 'vazevedo@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Victor Lutte',
                'email' => 'vlutte@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Victória Pinto Martins',
                'email' => 'vmartins@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vinicius Meloni dos Santos',
                'email' => 'vsantos@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vitor Ferreira de Almeida',
                'email' => 'valmeida@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vitoria Cristina Xavier',
                'email' => 'vxavier@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wagner Carneiro Alves',
                'email' => 'walves@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'William Rodrigues Batista',
                'email' => 'wbatista@tortillas.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
