<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'ALLAN NUNES BARREIROS',
                'email' => 'allannunesbarreiros@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANDERSON CARVALHO PEREIRA',
                'email' => 'andpereira30@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANDRE LUIZ DOS SANTOS PAIXAO',
                'email' => 'andreluiz090304@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CHRISTIANO JORGE DA SILVA',
                'email' => 'christianojorgesilva@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ELENICE DA CRUZ',
                'email' => 'elenicecruz43@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'EMERSON LUIS SOUZA DA SILVA',
                'email' => 'stuartsilvasouza@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FELIPE POLCENO DE ARAUJO',
                'email' => 'felipepolceno36@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ADRIANA DE SOUZA BARBOSA',
                'email' => 'ab443025@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ADRIANA FERREIRA COELHO',
                'email' => 'adrianaf_10@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANDREIA CRISTINA GONÇALVES',
                'email' => 'andreiablack802@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GILVAN ALVES DE FREITAS',
                'email' => 'gilvfreitas@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JESSICA RAMOS BORSATO CLEMENTE',
                'email' => 'jessicaborsato@gmail.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JOAO GABRIEL ROCHA DA CRUZ',
                'email' => 'joaogabrielrochacruz201@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUANA APARECIDA VIEIRA CARVALHO GOMES',
                'email' => 'luana.carvalho179@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUIS ARTHUR DA SILVA PINTO PINHEIRO',
                'email' => 'luisarthur389m@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARESSA VIEIRA FERREIRA',
                'email' => 'maressavieiraferreira@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARIA CLARA ESTEVES MAURÍCIO',
                'email' => 'mariaclaraesteves3rios@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARIA MADALENA RAMOS BONATTO',
                'email' => 'madahbonatto1004@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MAURO AUGUSTO FELIX',
                'email' => 'mauro_a_felix@yahoo.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MAXWELL GUIMARAES CARDOSO',
                'email' => 'maxwellguimaraesc@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NAYARA GENTIL DA SILVA',
                'email' => 'silvanay439@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAFAELA DE LIMA BARBOSA',
                'email' => 'rafaeladelimabarbosa79@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ROBERTA DE OLIVEIRA GIOVANINI',
                'email' => 'robertagiovanini6@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'THALYS GOMES DOS SANTOS',
                'email' => 'thalysgomes095@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VIVIANE APARECIDA PEREIRA DA CONCEICAO',
                'email' => 'vivianepviviane120@gmail.cm',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ALEXANDRE GOMES BALTAR',
                'email' => 'baltar417@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANDRE LUIZ DE SOUZA BRAMUNCHENKEL',
                'email' => 'alsbgaviao405@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANGELICA TEIXEIRA QUADROS',
                'email' => 'angelica.rics@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ARTHUR CARVALHO LAURINDO',
                'email' => 'arthurlaurindo.ti@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BRUNO DE OLIVEIRA SALVADOR',
                'email' => 'brunokbx@live.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DEBORA DA SILVA FURTADO',
                'email' => 'deborasilvarosa0@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DOUGLAS DE CASTRO DA SILVA',
                'email' => 'douglas-c-silva@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'EBANO GEORGE ALENCAR DE ALMEIDA',
                'email' => 'ebano776@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FABIANA DE OLIVEIRA AMORIM',
                'email' => 'fabianaemarcosrizo@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FABIO ARTHUR CAMACHO DE AZEREDO',
                'email' => 'arthurfabio535@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FELIPE GONÇALVES GUIMARAES',
                'email' => 'fgg1989@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FERNANDA GONÇALVES',
                'email' => 'fernadacsj@gmail.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FERNANDA MOREIRA SILVA',
                'email' => 'fernanda.moreira@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FRANCISCO MATEUS PAIVA DE OLIVEIRA FREITAS',
                'email' => 'matteuso58@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IANDRA GEISA SANTOS MARQUES',
                'email' => 'iandramarquess@outlook.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ISABELA PINTO DOS SANTOS CORDEIRO',
                'email' => 'isabelapinto@msn.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ISMAEL SILVA MATIAS',
                'email' => 'maelgreta@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JAQUELINE MARINHO DE CASTRO',
                'email' => 'jaquelinemclulu@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JOAO EVANGELISTA SANTOS FERREIRA',
                'email' => 'joaocafe52@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JOAO PEDRO ROCHA SIQUEIRA',
                'email' => 'joaopedro_rochasiqueira@yahoo.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JORGE LUIZ NUNES LUZORIO',
                'email' => 'jorgeluzorio@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JOSE FILIPE CANELLA DE MORAES',
                'email' => 'josefilipeca@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JULIA RODRIGUES GAGO ANDRADE',
                'email' => 'juliagago89@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JULIANE LOPES DA SILVA',
                'email' => 'julianelopess2014@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KARINE VIANA BARRETO PINTO',
                'email' => 'barreto.karine@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LARISSA MELO REBELO LIMA',
                'email' => 'larissamelorlima@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LEANDRO DA SILVA OLIVEIRA',
                'email' => 'leandrodasilvaoliveira@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUAN MIGUEL PEREIRA ZO CAVALCANTI',
                'email' => 'luanmiguuelzo@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUIZ PHILIPE ROCHA DE OLIVEIRA',
                'email' => 'phe_rdo@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARCOS VINICIUS GONÇALVES WERLY',
                'email' => 'viniwerly@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARIANA MAGALHAES PINTO',
                'email' => 'mmgpinto@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MATHEUS REZENDE GAMA',
                'email' => 'rezendegama06@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MICHELE MACEDO COUTINHO',
                'email' => 'michelemacedocoutinhomacedo@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MIRIA DA SILVA DE ANDRADE',
                'email' => 'miriysilva25@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NEILO PINTO CARNEIRO',
                'email' => 'neilopc@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PAMMELLA LIMA DE SOUZA',
                'email' => 'pammellalima2724@gmail.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PEDRO HENRIQUE REIS DA SILVA',
                'email' => 'reisp7788@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PEDRO MARTINS ALBUQUERQUE',
                'email' => 'pedromartiins6@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAFAEL DE OLIVEIRA MARCELINO',
                'email' => 'fredexbelem@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAFAEL LEAL DO NASCIMENTO',
                'email' => 'lealnascimento13@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAFAELLA MENDES FORTUNATO',
                'email' => 'mendesrafaella86@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RENATA GRALATO DO NASCIMENTO ARAUJO',
                'email' => 'renatagralato@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ROSEMARY SOUSA DA RESSURREIÇÃO',
                'email' => 'rosemary14souzaressurreicao@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ROSIANE DE SOUZA SILVA LOPES',
                'email' => 'nanesouzalopes555@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SARAH IANAE GUETHS LAGUNA',
                'email' => 'sarahiglaguna@hormail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SEVERINA GERLANI DA SILVA MONTEIRO',
                'email' => 'gerlainevellyn@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'STEFANY ALVES SILVA DE ALMEIDA',
                'email' => 'stefanyalvs@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TAIANA SANTANA FRANCA',
                'email' => 'taiana_santana17@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TATIANA CORDEIRO RIBEIRO',
                'email' => 'tatianacordeiro41@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'THAIS DA SILVA E SILVA',
                'email' => 'thaissilva.t2s@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'THAMIRES FERNANDES MACHADO',
                'email' => 'thamiresgrativolmac@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VAGNER FONSECA DA CONCEICAO',
                'email' => 'vagnerfonseca2010@bol.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VANESSA SOARES DE AZEVEDO',
                'email' => 'vanessa1984soares@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VICTORIA PINTO MARTINS',
                'email' => 'victoriapintomartins@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VINICIUS CURTY DE FREITAS',
                'email' => 'viniciuscurtydf@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'WAGNER FECHER OLIVEIRA DA SILVA',
                'email' => 'wagnerfecher02@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ABIGAIL DIAS DOS SANTOS',
                'email' => 'abigaildiassantos23@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ALEIXO TELES',
                'email' => 'catolica_ecciza10@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ALEXANDRE DA SILVA LIMA JUNIOR',
                'email' => 'silvaalexandre733@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ALMIR MACEDO JUNIOR',
                'email' => 'almirmacedojunior@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ALTAIR NAZARIO DE FIGUEIREDO',
                'email' => 'altairnazario02@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANDERSON DE AGUIAR REBECCHI',
                'email' => 'ninotricolor72@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANDRE DE OLIVEIRA GERMINIANO',
                'email' => 'germinianoandre89@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'name' => 'ANDRE RIOS LEMOS',
            //     'email' => '',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('12345678'),
            //     'role' => 'user',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'name' => 'ANDRESSA LANDIM BARBOSA',
                'email' => 'dedelandimb@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANTONIO DA SILVA CASTRO',
                'email' => 'antoniobuque55@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ARTHUR PONTES MELONI DOS REIS',
                'email' => 'arthurpmr10@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ATILA DE OLIVEIRA GERVAZIO PENKUHN',
                'email' => 'atilaoli712@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CAIO CESAR OURIQUE DA SILVA',
                'email' => 'ouriquecaio1@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CAIO MENEZES REPANI DE AZEVEDO',
                'email' => 'caio.menezesrepani@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CARLOS EDUARDO DO CANTO MARQUES',
                'email' => 'carloscanto50@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'COSME PENA VIANA',
                'email' => 'cosmeviana62@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CRISTIANE HILARIA DE SOUZA',
                'email' => 'spetersonp@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CRISTIANE LOPES NARCIZO',
                'email' => 'cristianelopesnarcizo@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CRISTIANO PIRES DE SOUZA',
                'email' => 'cp5460389@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CRISTIANO RIBEIRO VIEIRA',
                'email' => 'tianinhoribeiro@gmail.om',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DAIANI MORAES CONCEICAO GUIMARAES',
                'email' => 'daianiedu@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DANIEL DE SOUZA PIRES',
                'email' => 'daniel.pires@unigranrio.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DANIEL MARTINS PEREIRA SILVA',
                'email' => 'dn240silva@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DANIEL RODRIGO PEREIRA DO NASCIMENTO',
                'email' => 'danielrodrigo465@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DIEGO JUNIOR AMORIM PAIVA',
                'email' => 'diegojr537@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DIEGO VAZ GOMES  VIANA',
                'email' => 'diegovazgomesviana89@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DIOGO DA CONCEICAO CAMARA LOPES',
                'email' => 'diogolopes0104@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DORILAN ROSA VIEIRA XAVIER',
                'email' => 'dorilanrosavieira@yahoo.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ELIANE FERREIRA DA SILVA LEMOS',
                'email' => 'elianelemos455@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ELIAS SOARES FERREIRA',
                'email' => 'eliasnatosophi@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ELIZABETH DA SILVA GONÇALVES DOS SANTOS',
                'email' => 'kevingoncalves219@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ELMANO DAVI TRISTAO',
                'email' => 'elmanodavi09@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ERIC BILE ARRUDA DOS SANTOS',
                'email' => 'erickbile408@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'EVERTON FERREIRA LOPES',
                'email' => 'ev.lopes16@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FABIANO GUARNIERI AQUINO',
                'email' => 'fabiano_guarnieri@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'name' => 'FABRICIO KRUGER BREMIKAMP',
            //     'email' => '',
            //     'email_verified_at' => now(),
            //     'password' => Hash::make('12345678'),
            //     'role' => 'user',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            [
                'name' => 'FAGNO LIMA FIGUEIREDO',
                'email' => 'ianafrutuoso@outlook.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GABRIEL DOS SANTOS BARCELLO',
                'email' => 'gabrielbarcello1313@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GABRIEL PIRES LOPES',
                'email' => 'gabriel0974932@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GABRIELA FERRAZ SIQUEIRA',
                'email' => 'gabiferraz020@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GILMAR LOURENCO REZENDE JUNIOR',
                'email' => 'gilmar.rezende172@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GUILHERME RAMOS PINTO',
                'email' => 'pontramos2017@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GUSTAVO QUINTEIRO LIMA',
                'email' => 'gustavo27.limaa@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HENRIQUE ANDRADE DA FONSECA',
                'email' => 'henriquefonseca5220@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HESTEFFANI DE OLIVEIRA MARTELETE',
                'email' => 'hesteffani@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HIGOR MENEGUSSI XAVIER',
                'email' => 'higor.m.xavier23@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IAN FRANCA DE ALMEIDA',
                'email' => 'iannalmmeida@icloud.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IAN SERRADO FRUTUOSO',
                'email' => 'ianserrado03@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IGOR MARTELETE DA SILVA',
                'email' => 'igormsilva50@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IONAN SERRADO FRUTUOSO',
                'email' => 'ionanserrado90@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ISABELA SERRADO FRUTUOSO',
                'email' => 'isabela-serrado13@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ISABELLE LAIS SANTANNA AMORIM',
                'email' => 'isah123321love@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ISAIAS DA SILVA OLIVEIRA AMORIM',
                'email' => 'amorimbr321@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ISETE MARIA PEREIRA NASCENTE',
                'email' => 'marianascente7@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ITALO DA ROCHA DIAS SILVA',
                'email' => 'itallomaraquinha@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JAIME GONÇALVES DE ABREU',
                'email' => 'jaimegoncalves32255@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JANAINA VALENTIM DA SILVA',
                'email' => 'janar.d.o@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JEFFERSON DE PINHO ANACLETO',
                'email' => 'jefferson.cpl@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JESSE MACHADO DE OLIVEIRA',
                'email' => 'jessemachadodeoliveira@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JESSE ROCHA DA CUNHA',
                'email' => 'jesse_rcunha@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JHONE DE ANDRADE BARBOSA',
                'email' => 'jhoneandrade75@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JOABE DA SILVA FONSECA',
                'email' => 'joabezorro@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JOAO FELIPE CARNEIRO MAGALHAES',
                'email' => 'joaofelipeandrade18@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JOAO VICTOR DA SILVA DIAS',
                'email' => 'jvdias2203@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JOETH PEREIRA RAMOS',
                'email' => 'joethpereira@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JOSUE MACHADO DE OLIVEIRA',
                'email' => 'josuemachadodeoliveira30@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JULIA ROSSI GUIMARAES',
                'email' => 'juliarossieu@icloud.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JULIO CESAR DEMARCE SAMPAIO',
                'email' => 'sampaiojulio86@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KAUA SANTOS DE ALMEIDA',
                'email' => 'kauasantosalmeida06@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KEVIN LEAL OURIQUE DE CARVALHO',
                'email' => 'kevin.ourique@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LARISSA DA SILVA PINTO',
                'email' => 'dsp.larissa@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LEONARDO CUNHA DIAS',
                'email' => 'leodias0468@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LEONARDO SANTOS FRANCO',
                'email' => 'leofranco96@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LILIANA MEDRANO DE SOUZA',
                'email' => 'enzofelipecarmo755@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LINDIOMAR NAZARIO DE FIGUEIREDO',
                'email' => 'eunazario3@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUANA APARECIDA DE OLIVEIRA PIRES',
                'email' => 'oliveiraluana756@yahoo.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUCAS DE CASTRO GONCALVES',
                'email' => 'lucascastrog29@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUCIANA LEAL DA SILVA OURIQUE DE CARVALHO',
                'email' => 'lucianaleal111070@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUCIANO PICONI FURTADO',
                'email' => 'lucianofurtado788@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUCIMAR MACEDO QUADROS NASCIMENTO',
                'email' => 'lucimar.quadros.lq@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUIS FERNANDO DE OLIVEIRA LEMOS',
                'email' => 'luissequoia123@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUIZ AUGUSTO BENEVENTE BITTENCOURT',
                'email' => 'gutobittencourt87@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARCIA CRISTINA BARBOSA CORDEIRO',
                'email' => 'marcyabarboza@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARCILENE VIANA LOPES',
                'email' => 'marcilene.lopes936612@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARCUS VINÍCIUS DOS SANTOS BRAGA',
                'email' => 'marcusviniciussbraga@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARIA LUIZA CAMACHO BATISTA',
                'email' => 'malubatistabatista@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARIA LUIZA SOARES DA SILVA',
                'email' => 'marialuizasoares1209@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARIA REGINA FERREIRA DOS SANTOS',
                'email' => 'regina.ferreira1993@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MICHEL DEMARCE SAMPAIO',
                'email' => 'micheldemarce9@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NATALIA LOPES TAVARES',
                'email' => 'natalia_16tavares@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NAYARA CABRAL DOS SANTOS',
                'email' => 'nayaracabralsantos@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NILTA LEANDRO',
                'email' => 'niltaleandro6@outlook.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ODIRLEI MARIANO PINHEIRO',
                'email' => 'odirleimp@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PATRICIA DE SIQUEIRA',
                'email' => 'pattysiqueira147@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PEDRO HENRIQUE LARANJEIRA TEIXEIRA PINTO',
                'email' => 'pedrolaranjeira09@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PEDRO JOSE BARBOSA REPANI',
                'email' => 'pedrorepani@outlook.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PEDRO LUCAS OLIVEIRA FERRAZ E SILVA',
                'email' => 'pedroolferraz@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PHILLIPE FREITAS DE OLIVEIRA',
                'email' => 'phillfreitasdeoliveira@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PRISCILA MUZI ALVES',
                'email' => 'priscila.muzi@yahoo.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAFAEL DO NASCIMENTO DA SILVA',
                'email' => 'rafael2006010@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAFAEL SIQUEIRA MELONI',
                'email' => 'rafasmeloni@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'REBECA HERCULANO MENEZES',
                'email' => 'rebecamenezes67@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'REDRIK MACHADO CALDEIRA',
                'email' => 'redrikmc@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RENAN RAMOS D ANUNCIACAO',
                'email' => 'renanramos637@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SAMARA SOARES DA SILVA',
                'email' => 'samaras2protegida@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SAMUEL REIS VIANA',
                'email' => 'samuelreisviana@icloud.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SARA SOARES TOBIAS DA COSTA',
                'email' => 'stobiasmoreira@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SUELI GOMES DE ARAUJO',
                'email' => 'sueliigomesdearaujo@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SUELLEM CARLA AMORIM DE ARRUDA',
                'email' => 'suellenarruda87@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TAIGUARA DA SILVA',
                'email' => 'taiguaradasilva382@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TATYANE VIEIRA MARCHIORO',
                'email' => 'tatyvm@outlook.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'THIAGO PEREIRA DE SOUZA',
                'email' => 'thiagotim1@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TIAGO DE SOUZA PIRES',
                'email' => 'tiagoneguet.tjf@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'UBIRACI GOMES FERREIRA',
                'email' => 'dilmaegoita@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'UELLINTON PAULA DOS SANTOS',
                'email' => 'uellintonpaulasantos@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VALCILEA DE OLIVEIRA FERRAZ',
                'email' => 'valcilea0806@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VANESSA LOPES DA SILVA',
                'email' => 'vanessa.macae@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VINICIUS RANGEL DE JESUS',
                'email' => 'rangelvinicius92@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VITOR FERREIRA DE ALMEIDA',
                'email' => 'vitor.ferreiraa@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'WENDEL DA SILVA MAGALHÃES',
                'email' => 'wendelmagalhaes82@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'WESLEY BORGES DE SOUZA',
                'email' => 'wlbsouza@outlook.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'WEVERTON DIAS LIAL',
                'email' => 'wevertonlial01@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ALFREDO ANTONIO RODRIGUEZ RAMIREZ',
                'email' => 'israelprime6987@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CAIO GONÇALVES CANDIDO',
                'email' => 'caio.gcandido@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DANILLO HENRIQUE AUGUSTO AGUIAR',
                'email' => 'danillohenriqueaugusto@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DOMINGOS SOARES LEAO',
                'email' => 'domingos.soares1985@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ERIC MEDINA GONCALVES DE SOUSA',
                'email' => 'ericmedinags@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'EUDISMAR ALVES MENDES',
                'email' => 'eudesmar0222@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GUILHERME CORREA E SILVA',
                'email' => 'guilhermecorrea492@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MANUELLA VILAR PEREIRA DA SILVA',
                'email' => 'manuellavilar3@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PAMELA DE LIMA OLIVEIRA',
                'email' => 'ppamelinhalimaoliveira@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'WILLIAM RODRIGUES BATISTA',
                'email' => 'willianrodri31@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ELTON DOS SANTOS',
                'email' => 'eltonsantos100@hotmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PAULA LOPES DA SILVA PINTO',
                'email' => 'paulalpinto@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('12345678'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
